### ISSUE TITLE
Staging Server - New Report Fails on desktop when adding an image from hard disk

### ISSUE THREAD

**Issue by carlitos816** [DaanMatch/FieldWorker#25]
Record Data = "test2"

Screen shot:
<img width="866" alt="Screen Shot 2022-01-19 at 7 11 48 PM" src="https://user-images.githubusercontent.com/70997559/150266282-07fc421a-6b7d-4ecf-9dac-7c84d5951120.png">

The upload image (under 1mb)
![CR-headshot2](https://user-images.githubusercontent.com/70997559/150266448-c1027839-2133-4561-bbf7-eb1d6e943ba2.jpg)

**Comment by biofool** [comment]
Please retest on dev.  I am upgrading stage also.

**Comment by biofool** [comment]
https://github.com/DaanMatch/FieldWorker/commit/2dd6bd66fa5d9d1236428dbfb9a4d9ab5a970cb7
