### ISSUE TITLE
Register fields format

### ISSUE THREAD

**Issue by shpatrickguo** [DaanMatch/FieldWorker#8]
![image](https://user-images.githubusercontent.com/70539478/147840156-f89ed8a3-ab04-4426-a10c-00ebde12858b.png)

**Comment by carlitos816** [comment]
input fields need class"field" added to their html.

`

<input name="username" id="username" required>
--
  | <div class="fcf-form-group">
  | <label for="Email" class="fcf-label">Your email address</label>
  | <input type="email" id="email" name="email" class="fcf-form-control" >
  | </div>
  | <div class="fcf-form-group">
  | <label for="Phone" class="fcf-label">Your phone #</label>
  | <input type="tel" id="phone" name="phone" class="fcf-form-control" >
  | </div>
  | <label for="ngo_name">NGO Name</label>
  | <input name="ngo_name" id="ngo_name" required>
  | <label for="gran_p">Gram Panchayat</label>
  | <input name="gram_p" id="gram_p" required>

**Comment by biofool** [comment]
class"field" added
